# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Image',
            field=models.ImageField(default=True, upload_to='Images/'),
        ),
    ]
