# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
