# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0003_auto_20181005_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
    ]
