# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0004_auto_20181006_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='image',
        ),
    ]
