# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0009_auto_20190522_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='defaul.jpg', upload_to='prof/'),
        ),
    ]
